version: '3'
services:
  mysql:
    build:
      dockerfile: Dockerfile
      context: ./db/
    ports:
      - '3306:3306'
      - '9002:9002'
    expose:
      - 3306
      - 9002
    healthcheck:
        test: ["CMD", "curl", "-f", "http://localhost:9002"]
        interval: 30s
        timeout: 10s
        retries: 5
  srv:
    build:
      dockerfile: Dockerfile
      context: .
    restart: always
    command: sh -c "/wait"
    environment:
      - WAIT_HOSTS=mysql:3306
      - WAIT_HOSTS_TIMEOUT=300
      - WAIT_SLEEP_INTERVAL=30
      - WAIT_HOST_CONNECT_TIMEOUT=30
    depends_on:
      - mysql
    ports:
      - '9001:80'
    expose:
      - 80
      - 9001

